services:
  # Combined Bot, API, and Dashboard Service
  - type: web
    name: sacudo
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      cd dashboard && npm install && npm run build
    startCommand: python bot.py --with-api
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_PORT
        value: 8000
    healthCheckPath: /api/debug
    autoDeploy: true 